▽base: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  pool: 5
  username: <%= ENV.fetch('POSTGRES_USER', 'root') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', '') %>
  host: <%= ENV.fetch('POSTGRESQL_PORT_5432_TCP_ADDR', '') %>
  port: <%= ENV.fetch('POSTGRESQL_PORT_5432_TCP_PORT', '5432') %>
  database: hound_<%= ENV.fetch('RAILS_ENV', '') %>
  prepared_statements: false
  pool: <%= ENV.fetch("DB_POOL", 5) %>
  reaping_frequency: <%= ENV.fetch("DB_REAPING_FREQUENCY", 10) %>

development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 10
  database: hound_dev
  port: 5432

staging:
  <<: *default

test:
  <<: *default
  database: hound_test

production:
  pool: <%= [ENV.fetch("MAX_THREADS", 5), ENV.fetch("DB_POOL", 5)].max %>
  url:  <%= ENV.fetch("DATABASE_URL") if Rails.env.production? %>
